meal_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from meal_planners import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meal_planners.urls')),
    path('users/', include('users.urls')),
]

meal_planners/urls.py
"""Defines URL patterns for meal_planners"""

from django.urls import path
from . import views

app_name = 'meal_planners'

urlpatterns = [
    # Home page
    path('', views.index, name = 'index'),

    # Recipes page
    path('recipes/', views.recipes, name = 'recipes'),

    # Detailed page for each recipe
    path('recipes/<int:recipe_id>/', views.recipe, name = 'recipe'),

    # Page for adding new recipe
    path('recipes/new_recipe/', views.new_recipe, name = 'new_recipe'),

    # Page for adding details of a recipe (description, labels...)
    path('recipes/new_recipe/<int:recipe_id>/', views.new_recipe_details, name = 'new_recipe_details'),

    # Page for editing an existing recipe
    path('recipes/edit_recipe/<int:recipe_id>/', views.edit_recipe, name = 'edit_recipe'),

    # URL to delete recipe
    path('recipes/delete_recipe/<int:recipe_id>/', views.delete_recipe, name = 'delete_recipe'),

    # URL for the recipes picker
    path('recipes_picker/', views.get_random_recipe, name = 'recipes_picker'),
]

users/urls.py
"""Defines url patterns for users."""

from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'
urlpatterns = [
	# Login page.
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),

    # Logout Page
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    # Registration page
    path('register/', views.register, name='register'),
]

meal_planners/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Recipe(models.Model):
    """A recipe that the user can create and view"""
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model"""
        return self.name

class Description(models.Model):
    """A description of the recipe"""
    recipe = models.ForeignKey(Recipe, on_delete = models.CASCADE)
    text = models.TextField(default="Please enter description of your recipe")

    def __str__(self):
        """Return a string representation of the model"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

meal_planners/forms.py
from django import forms

from .models import Recipe, Description

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name']
        labels = {'name':''}

class DescriptionForm(forms.ModelForm):
    class Meta:
        model = Description
        fields = ['text']
        labels = {'text':''}

meal_planners/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Recipe, Description
from .forms import RecipeForm, DescriptionForm
from .recipes_picker import random_recipe
# Create your views here.

def index(request):
    """The home page for Meal Planner"""
    return render(request, 'meal_planners/index.html')

@login_required
def recipes(request):
    """Show all recipes"""
    recipes = Recipe.objects.filter(owner=request.user).order_by('name')
    context = {'recipes' : recipes}
    return render(request, 'meal_planners/recipes.html', context)

@login_required
def recipe(request, recipe_id):
    """Show a single recipe and its description"""
    recipe = Recipe.objects.get(id=recipe_id)

    # Make sure the recipe belongs to the current user
    if recipe.owner != request.user:
        raise Http404

    descriptions = recipe.description_set.all()
    context = {'recipe': recipe, 'descriptions': descriptions}
    return render(request, 'meal_planners/recipe.html', context)

@login_required
def new_recipe(request):
    """Add a new recipe"""
    # Cannot add several forms on the recipe creation page as all children forms (description, labels...) require a recipe_id that is only assigned after recipe description
    if request.method != 'POST':
        # No data submitted, create a blank form to start creating a new recipe
        form = RecipeForm()
    else:
        # New recipe submitted via POST method, process data
        form = RecipeForm(data=request.POST)
        if form.is_valid():
            new_recipe = form.save(commit=False)
            new_recipe.owner = request.user
            new_recipe.save()
            return HttpResponseRedirect(reverse('meal_planners:new_recipe_details', args=[new_recipe.pk]))

    context = {'form': form}
    return render (request, 'meal_planners/new_recipe.html', context)

@login_required
def new_recipe_details(request, recipe_id):
    """Add a new description to a recipe that has just been created"""
    # Can add several forms on the same page: description, labels,... by using form1, form2 and so on as long as we receive recipe_id
    recipe = Recipe.objects.get(id=recipe_id)

    # Make sure the recipe belongs to the current user
    if recipe.owner != request.user:
        raise Http40

    if request.method != 'POST':
        # No data available, create a blank form. 
        form1 = DescriptionForm()
    else:
        # New details submitted via POST method, process data
        form1 = DescriptionForm(data=request.POST)
        if form1.is_valid():
            new_description = form1.save(commit=False)
            new_description.recipe = recipe
            new_description.save()
            return HttpResponseRedirect(reverse('meal_planners:recipe', args=[recipe_id]))

    context = {'recipe': recipe, 'form1': form1}
    return render (request, 'meal_planners/new_recipe_details.html', context)

@login_required
def edit_recipe(request, recipe_id):
    """Edit an existing recipe"""
    name = Recipe.objects.get(id = recipe_id)
    description = Description.objects.get(recipe_id=recipe_id)
    recipe = description.recipe

    # Make sure the recipe belongs to the current user
    if recipe.owner != request.user:
        raise Http40

    if request.method != 'POST':
        # Initial request, view the forms with the current recipe
        form1 = RecipeForm(instance = name)
        form2 = DescriptionForm(instance = description)

    else:
        # Post data to update the recipe
        form1 = RecipeForm(instance = name, data=request.POST)
        form2 = DescriptionForm(instance = description, data=request.POST)
        if form1.is_valid() and form2.is_valid():
            form1.save()
            form2.save()
            return HttpResponseRedirect(reverse('meal_planners:recipe', args=[recipe_id]))

    context = {'name': name, 'recipe': recipe, 'description': description, 'form1': form1, 'form2': form2}
    return render(request, 'meal_planners/edit_recipe.html', context)

@login_required
def delete_recipe(request, recipe_id):
    """Delete a recipe"""
    if request.method == 'POST':
        name = Recipe.objects.get(id = recipe_id)
        description = Description.objects.get(recipe_id=recipe_id)
        recipe = description.recipe

        description.delete()
        name.delete()
        return HttpResponseRedirect (reverse('meal_planners:recipes'))
       
    context = {'name': name, 'description': description, 'recipe': recipe}
    return render(request, 'meal_planners/recipes.html', context)

@login_required
def get_random_recipe(request):
    """Return a random recipe"""
    days = range(0,7)
    random_recipe()
    
    context = {'random_recipe': random_recipe, 'days': days}
    return render(request, 'meal_planners/recipes_picker.html', context)

users/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def register(request):
    """Register a new user"""
    if request.method != 'POST':
        # Dispay blank registration form
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data = request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and then rediract to home page
            authenticated_user = authenticate(username=new_user.username, password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('meal_planners:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

meal_planners/templates/meal_planners/base.html
<p>
    <a href="{% url 'meal_planners:index' %}">Meal Planner</a>
    <a href="{% url 'meal_planners:recipes' %}">Recipes</a>
    <a href="{% url 'meal_planners:recipes_picker' %}">Recipe picker</a> -
    {% if user.is_authenticated %}
        Hello, {{ user.username }}.
        <a href="{% url 'users:logout' %}">log out</a>
    {% else %}
        <a href="{% url 'users:register' %}">register</a>
        <a href="{% url 'users:login' %}">log in</a>
    {% endif %}
</p>

{% block content%}{%endblock content %}

meal_planners/templates/meal_planners/edit_recipe.html
{%extends "meal_planners/base.html" %}

{% block content %}

    <p>Edit Recipe</p>
    <p>Name: {{ recipe }}</p>
    <p>Description: 
    <form action="{% url 'meal_planners:edit_recipe' recipe.id %}" method = 'post'>
        {% csrf_token %}
        {{ form1.as_p }}
        {{ form2.as_p }}
        <button name = "submit">save changes</button>
    </form>
    <form action="{% url 'meal_planners:recipe' recipe.id %}">
        <input type="submit" value="cancel" />
    </form>
    </p>

{% endblock content %}

meal_planners/templates/meal_planners/index.html
{%extends "meal_planners/base.html" %}

{% block content %}
    <p>Hello</p>
    <p>This website allows you to:</p>
    <ul>
        <li>Add your receipes to your list</li>
        <li>See a meal planner over the next 7 days based on a random selection of your recipes (COMING SOON...)</li>
        <li>Define rules so that the meal planners pickes relevant and varied recipes (COMING...)</li>
    </ul>
{% endblock content %}

meal_planners/templates/meal_planners/new_recipe.html
{%extends "meal_planners/base.html" %}

{% block content %}
    <p>Add a new recipe</p>
    <form action="{%url 'meal_planners:new_recipe' %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add recipe</button>
    </form>
    
{% endblock content %}

meal_planners/templates/meal_planners/new_recipe_details.html
{%extends "meal_planners/base.html" %}

{% block content %}

    <p>{{ recipe }}</p>

    <p>Add a description for your recipe</p>
    <form action="{% url 'meal_planners:new_recipe_details' recipe.id %}" method = 'POST'>
        {% csrf_token %}
        {{ form1.as_p }}
        <button name = 'submit'>Add details</button>
    </form>

{% endblock content %}

meal_planners/templates/meal_planners/recipe.html
{%extends "meal_planners/base.html" %}

{% block content %}
   
    <p>Recipe: {{ recipe }}</p>

    {% for description in descriptions %}
        <p>Description: {{ description.text|linebreaks }}</p>
        <p>
            <a href="{% url 'meal_planners:edit_recipe' recipe.id %}">Edit recipe</a>
        </p>
    {% empty %}
        <p>No description for this recipe</p>
        <p>
            <a href="{% url 'meal_planners:new_recipe_details' recipe.id %}">Add recipe details</a>
        </p>
    {% endfor %}
    
    <form action="{% url 'meal_planners:delete_recipe' recipe.id %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete recipe"/>
      </form>

{% endblock content %}

meal_planners/templates/meal_planners/recipes.html
{%extends "meal_planners/base.html" %}

{% block content %}
   
    <p>Recipes</p>

    <a href="{% url 'meal_planners:new_recipe'%}">Add a new recipe</a> 
    <br><br>

    <table>
        <tr>
            <th>Recipe Name</th>
        </tr>
        
        {% for recipe in recipes %}
            <tr>
                <td><a href="{% url 'meal_planners:recipe' recipe.id %}">{{ recipe }}</a></td>
            </tr>

        {% empty %}
            <tr>
                <td>No recipe added yet</td>
            </tr>
        {% endfor %}
        
    </table>
{% endblock content %}

meal_planners/templates/meal_planners/recipes_picker.html
{%extends "meal_planners/base.html" %}

{% block content %}

    <table>
        <tr>
            <th>Day 1</th>
            <th>Day 2</th>
            <th>Day 3</th>
            <th>Day 4</th>
            <th>Day 5</th>
            <th>Day 6</th>
            <th>Day 7</th>
        </tr>
        <tr>
        {% for day in days %}
            <td>{{ random_recipe }}</a></td>
        
        {% empty %}
            <td>No recipe added yet</td>

        {% endfor %}
        </tr>
        
    </table>

{% endblock content %}

users/templates/users/login.html
{% extends 'meal_planners/base.html' %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again</p>
    {% endif %}

    <form method='post' action="{%url 'users:login' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">log in</button>
        <input type="hidden" name="next" value = "{% url 'meal_planners:index' %}" />
    </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'meal_planners/base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        <p> Hello, {{ user.username }}. You are already logged in. Please log out first if you want to register a new account.</p>

    {% else %}
        <form method='post' action="{% url 'users:register' %}">
            {% csrf_token %}
            {{ form.as_p }}

            <button name="submit">register</button>
            <input type="hidden" name = "next" value = "{ url 'meal_planners:index' %}"/>
        </form>

    {% endif %}

{% endblock content %}